"""add blacklist table

Revision ID: 95871cae4ff2
Revises: 7995498605c2
Create Date: 2019-03-22 13:04:55.063872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95871cae4ff2'
down_revision = '7995498605c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
